-- Migration 034: Alert title and description translation keys
--
-- Adds i18n keys for all alert messages generated by alerts.py.
-- Descriptions use {param} placeholders filled in by i18n.js at runtime.

INSERT INTO translation_keys (key, default_value, category, description) VALUES

-- Biennial currency (SFCL.160a)
('logbook.alert.currency_ok.title',    'Current biennial practice — SPL',       'logbook.alert', NULL),
('logbook.alert.currency_ok.desc',     '{time} and {launches} launches in the last 24 months — requirements met.', 'logbook.alert', NULL),
('logbook.alert.currency_low.title',   'Biennial currency low — SPL',            'logbook.alert', NULL),
('logbook.alert.currency_low.desc',    'SFCL.160(a) requires 5h + 15 launches in any 24-month window. Still needed: {missing}.', 'logbook.alert', NULL),

-- Launch method recency (SFCL.130) — generic keys, {method} substituted at runtime
('logbook.alert.launch_90.title',      'No {method} launch in over 90 days',     'logbook.alert', NULL),
('logbook.alert.launch_90.desc',       'Last {method} launch was {days} days ago. Consider a currency flight.', 'logbook.alert', NULL),
('logbook.alert.launch_180.title',     'No {method} launch in over 180 days',    'logbook.alert', NULL),
('logbook.alert.launch_180.desc',      'SFCL.130: privileges are restricted to methods passed in the practical exam. Last {method} launch was {days} days ago — refresher training recommended.', 'logbook.alert', NULL),

-- Passenger recency (FCL.060)
('logbook.alert.pax_recency.title',    'Recent experience — passenger carriage', 'logbook.alert', NULL),
('logbook.alert.pax_recency.desc',     'FCL.060: before carrying a passenger you need 3 take-offs and 3 landings as PIC in the last 90 days. Current: {flights} flights in the last 90 days.', 'logbook.alert', NULL),

-- Passenger thresholds (SFCL.115b)
('logbook.alert.pax_threshold_1.title','Passenger carriage — threshold 1',       'logbook.alert', NULL),
('logbook.alert.pax_threshold_1.desc', 'SFCL.115(b)(1): first passenger requires 10h PIC or 30 PIC launches. Current: {launches} PIC launches.', 'logbook.alert', NULL),
('logbook.alert.pax_threshold_2.title','Hire/reward flights — threshold 2',      'logbook.alert', NULL),
('logbook.alert.pax_threshold_2.desc', 'SFCL.115(b)(2): flights for hire/reward require 75h PIC or 200 PIC launches + proficiency check. Current: {launches} PIC launches.', 'logbook.alert', NULL),

-- Medical (Part-MED)
('logbook.alert.medical_missing.title','Medical certificate — no expiry date',   'logbook.alert', NULL),
('logbook.alert.medical_missing.desc', 'Enter your medical certificate expiry date in Settings so the system can remind you 60 days before it expires.', 'logbook.alert', NULL),
('logbook.alert.medical_expired.title','Medical certificate expired',             'logbook.alert', NULL),
('logbook.alert.medical_expired.desc', 'Your medical certificate expired {days} days ago. You cannot exercise the privileges of your licence until you renew it.', 'logbook.alert', NULL),
('logbook.alert.medical_soon.title',   'Medical certificate expiring soon',       'logbook.alert', NULL),
('logbook.alert.medical_soon.desc',    'Your medical certificate expires in {days} days ({expiry}). Schedule a renewal appointment.', 'logbook.alert', NULL),

-- Profile completeness
('logbook.alert.profile_license_date.title','SPL licence date not entered',      'logbook.alert', NULL),
('logbook.alert.profile_license_date.desc', 'Enter your SPL licence issue date in Settings. This is needed to accurately compute passenger-carriage thresholds (SFCL.115).', 'logbook.alert', NULL)

ON CONFLICT (key) DO NOTHING;


-- ─────────────────────────────────────────────────────────────────────────────
-- Polish (pl) translations
-- ─────────────────────────────────────────────────────────────────────────────
INSERT INTO translations (key_id, language_code, value)
SELECT id, 'pl', v FROM (VALUES

('logbook.alert.currency_ok.title',    'Aktualna praktyka bieżąca — SPL'),
('logbook.alert.currency_ok.desc',     '{time} i {launches} startów w ostatnich 24 miesiącach — wymagania spełnione.'),
('logbook.alert.currency_low.title',   'Niewystarczająca praktyka bieżąca — SPL'),
('logbook.alert.currency_low.desc',    'SFCL.160(a) wymaga 5h + 15 startów w ciągu 24 miesięcy. Brakuje: {missing}.'),

('logbook.alert.launch_90.title',      'Brak startu: {method} od ponad 90 dni'),
('logbook.alert.launch_90.desc',       'Ostatni start: {method} był {days} dni temu. Rozważ lot dla zachowania aktualności uprawnień.'),
('logbook.alert.launch_180.title',     'Brak startu: {method} od ponad 180 dni'),
('logbook.alert.launch_180.desc',      'SFCL.130: uprawnienia są ograniczone do metod zdanych na egzaminie. Ostatni start: {method} był {days} dni temu — zalecane szkolenie odświeżające.'),

('logbook.alert.pax_recency.title',    'Aktualne doświadczenie — lot z pasażerem'),
('logbook.alert.pax_recency.desc',     'FCL.060: przed lotem z pasażerem wymagane są 3 starty i 3 lądowania jako PIC w ciągu ostatnich 90 dni. Aktualnie: {flights} lotów w ostatnich 90 dniach.'),

('logbook.alert.pax_threshold_1.title','Lot z pasażerem — próg 1'),
('logbook.alert.pax_threshold_1.desc', 'SFCL.115(b)(1): lot z pierwszym pasażerem wymaga 10h PIC lub 30 startów PIC. Aktualnie: {launches} startów PIC.'),
('logbook.alert.pax_threshold_2.title','Loty zarobkowe — próg 2'),
('logbook.alert.pax_threshold_2.desc', 'SFCL.115(b)(2): loty za wynagrodzeniem wymagają 75h PIC lub 200 startów PIC + sprawdzian. Aktualnie: {launches} startów PIC.'),

('logbook.alert.medical_missing.title','Brak daty ważności orzeczenia lekarskiego'),
('logbook.alert.medical_missing.desc', 'Wprowadź datę ważności orzeczenia lekarskiego w Ustawieniach, aby system mógł przypominać 60 dni przed wygaśnięciem.'),
('logbook.alert.medical_expired.title','Orzeczenie lekarskie wygasło'),
('logbook.alert.medical_expired.desc', 'Twoje orzeczenie lekarskie wygasło {days} dni temu. Nie możesz korzystać z uprawnień licencji do czasu odnowienia.'),
('logbook.alert.medical_soon.title',   'Orzeczenie lekarskie wkrótce wygasa'),
('logbook.alert.medical_soon.desc',    'Twoje orzeczenie lekarskie wygasa za {days} dni ({expiry}). Zaplanuj wizytę odnowieniową.'),

('logbook.alert.profile_license_date.title','Nie podano daty uzyskania licencji SPL'),
('logbook.alert.profile_license_date.desc', 'Wprowadź datę uzyskania licencji SPL w Ustawieniach. Jest ona potrzebna do obliczenia progów dla lotów z pasażerami (SFCL.115).')

) AS t(k, v)
JOIN translation_keys ON translation_keys.key = t.k
ON CONFLICT (key_id, language_code) DO UPDATE SET value = EXCLUDED.value;


-- ─────────────────────────────────────────────────────────────────────────────
-- German (de) translations
-- ─────────────────────────────────────────────────────────────────────────────
INSERT INTO translations (key_id, language_code, value)
SELECT id, 'de', v FROM (VALUES

('logbook.alert.currency_ok.title',    'Aktuelle Übungswährigkeit — SPL'),
('logbook.alert.currency_ok.desc',     '{time} und {launches} Starts in den letzten 24 Monaten — Anforderungen erfüllt.'),
('logbook.alert.currency_low.title',   'Übungswährigkeit unzureichend — SPL'),
('logbook.alert.currency_low.desc',    'SFCL.160(a) erfordert 5h + 15 Starts in einem 24-Monats-Zeitraum. Noch benötigt: {missing}.'),

('logbook.alert.launch_90.title',      'Kein {method}-Start seit über 90 Tagen'),
('logbook.alert.launch_90.desc',       'Letzter {method}-Start war vor {days} Tagen. Erwägen Sie einen Währigkeitsflug.'),
('logbook.alert.launch_180.title',     'Kein {method}-Start seit über 180 Tagen'),
('logbook.alert.launch_180.desc',      'SFCL.130: Berechtigungen sind auf bestandene Startmethoden beschränkt. Letzter {method}-Start war vor {days} Tagen — Auffrischungsschulung empfohlen.'),

('logbook.alert.pax_recency.title',    'Aktuelle Erfahrung — Passagierbeförderung'),
('logbook.alert.pax_recency.desc',     'FCL.060: Vor der Passagierbeförderung sind 3 Starts und 3 Landungen als PIC in den letzten 90 Tagen erforderlich. Aktuell: {flights} Flüge in den letzten 90 Tagen.'),

('logbook.alert.pax_threshold_1.title','Passagierbeförderung — Schwellenwert 1'),
('logbook.alert.pax_threshold_1.desc', 'SFCL.115(b)(1): Erster Passagier erfordert 10h PIC oder 30 PIC-Starts. Aktuell: {launches} PIC-Starts.'),
('logbook.alert.pax_threshold_2.title','Entgeltflüge — Schwellenwert 2'),
('logbook.alert.pax_threshold_2.desc', 'SFCL.115(b)(2): Entgeltflüge erfordern 75h PIC oder 200 PIC-Starts + Befähigungsüberprüfung. Aktuell: {launches} PIC-Starts.'),

('logbook.alert.medical_missing.title','Tauglichkeitszeugnis — kein Ablaufdatum'),
('logbook.alert.medical_missing.desc', 'Geben Sie das Ablaufdatum Ihres Tauglichkeitszeugnisses in den Einstellungen ein, damit das System Sie 60 Tage vorher erinnern kann.'),
('logbook.alert.medical_expired.title','Tauglichkeitszeugnis abgelaufen'),
('logbook.alert.medical_expired.desc', 'Ihr Tauglichkeitszeugnis ist vor {days} Tagen abgelaufen. Sie dürfen die Rechte Ihrer Lizenz erst nach Erneuerung ausüben.'),
('logbook.alert.medical_soon.title',   'Tauglichkeitszeugnis läuft bald ab'),
('logbook.alert.medical_soon.desc',    'Ihr Tauglichkeitszeugnis läuft in {days} Tagen ab ({expiry}). Vereinbaren Sie einen Erneuerungstermin.'),

('logbook.alert.profile_license_date.title','SPL-Lizenzdatum nicht eingetragen'),
('logbook.alert.profile_license_date.desc', 'Geben Sie das Ausstellungsdatum Ihrer SPL-Lizenz in den Einstellungen ein. Es wird für die Berechnung der Passagierschwellen (SFCL.115) benötigt.')

) AS t(k, v)
JOIN translation_keys ON translation_keys.key = t.k
ON CONFLICT (key_id, language_code) DO UPDATE SET value = EXCLUDED.value;


-- ─────────────────────────────────────────────────────────────────────────────
-- Czech (cs) translations
-- ─────────────────────────────────────────────────────────────────────────────
INSERT INTO translations (key_id, language_code, value)
SELECT id, 'cs', v FROM (VALUES

('logbook.alert.currency_ok.title',    'Aktuální letová praxe — SPL'),
('logbook.alert.currency_ok.desc',     '{time} a {launches} startů za posledních 24 měsíců — požadavky splněny.'),
('logbook.alert.currency_low.title',   'Nedostatečná letová praxe — SPL'),
('logbook.alert.currency_low.desc',    'SFCL.160(a) vyžaduje 5h + 15 startů v libovolném 24měsíčním období. Stále chybí: {missing}.'),

('logbook.alert.launch_90.title',      'Žádný start: {method} více než 90 dní'),
('logbook.alert.launch_90.desc',       'Poslední start: {method} byl před {days} dny. Zvažte let pro udržení způsobilosti.'),
('logbook.alert.launch_180.title',     'Žádný start: {method} více než 180 dní'),
('logbook.alert.launch_180.desc',      'SFCL.130: oprávnění jsou omezena na metody absolvované při zkoušce. Poslední start: {method} byl před {days} dny — doporučuje se opakovací výcvik.'),

('logbook.alert.pax_recency.title',    'Aktuální zkušenost — přeprava cestujících'),
('logbook.alert.pax_recency.desc',     'FCL.060: před přepravou cestujícího jsou nutné 3 vzlety a 3 přistání jako PIC za posledních 90 dní. Aktuálně: {flights} letů za posledních 90 dní.'),

('logbook.alert.pax_threshold_1.title','Přeprava cestujících — práh 1'),
('logbook.alert.pax_threshold_1.desc', 'SFCL.115(b)(1): první cestující vyžaduje 10h PIC nebo 30 startů PIC. Aktuálně: {launches} startů PIC.'),
('logbook.alert.pax_threshold_2.title','Úplatné lety — práh 2'),
('logbook.alert.pax_threshold_2.desc', 'SFCL.115(b)(2): úplatné lety vyžadují 75h PIC nebo 200 startů PIC + přezkoušení. Aktuálně: {launches} startů PIC.'),

('logbook.alert.medical_missing.title','Zdravotní průkaz — chybí datum platnosti'),
('logbook.alert.medical_missing.desc', 'Zadejte datum platnosti zdravotního průkazu v Nastavení, aby vás systém mohl upozornit 60 dní před vypršením.'),
('logbook.alert.medical_expired.title','Zdravotní průkaz vypršel'),
('logbook.alert.medical_expired.desc', 'Váš zdravotní průkaz vypršel před {days} dny. Nemůžete vykonávat oprávnění licence do doby obnovení.'),
('logbook.alert.medical_soon.title',   'Zdravotní průkaz brzy vyprší'),
('logbook.alert.medical_soon.desc',    'Váš zdravotní průkaz vyprší za {days} dní ({expiry}). Naplánujte si obnovovací návštěvu.'),

('logbook.alert.profile_license_date.title','Datum vydání licence SPL není zadáno'),
('logbook.alert.profile_license_date.desc', 'Zadejte datum vydání licence SPL v Nastavení. Je potřebné pro výpočet prahů pro přepravu cestujících (SFCL.115).')

) AS t(k, v)
JOIN translation_keys ON translation_keys.key = t.k
ON CONFLICT (key_id, language_code) DO UPDATE SET value = EXCLUDED.value;
